// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeOA9RHecRuBJFG9leSoMUZgqeUSJt5fk',
    appId: '1:737186771026:web:4f6b37e681c737f147af8b',
    messagingSenderId: '737186771026',
    projectId: 'fruits-hub-ui',
    authDomain: 'fruits-hub-ui.firebaseapp.com',
    storageBucket: 'fruits-hub-ui.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQaNcVDQCPro9hKRuNw2CRSfHmAjeV6K0',
    appId: '1:737186771026:android:a176799129ea7c2b47af8b',
    messagingSenderId: '737186771026',
    projectId: 'fruits-hub-ui',
    storageBucket: 'fruits-hub-ui.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUYJVT1H629cqGtELlZVNhpnEsZe_iDBI',
    appId: '1:737186771026:ios:e770b8ba9933193d47af8b',
    messagingSenderId: '737186771026',
    projectId: 'fruits-hub-ui',
    storageBucket: 'fruits-hub-ui.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUYJVT1H629cqGtELlZVNhpnEsZe_iDBI',
    appId: '1:737186771026:ios:e770b8ba9933193d47af8b',
    messagingSenderId: '737186771026',
    projectId: 'fruits-hub-ui',
    storageBucket: 'fruits-hub-ui.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeOA9RHecRuBJFG9leSoMUZgqeUSJt5fk',
    appId: '1:737186771026:web:e3383ce712e8a7cd47af8b',
    messagingSenderId: '737186771026',
    projectId: 'fruits-hub-ui',
    authDomain: 'fruits-hub-ui.firebaseapp.com',
    storageBucket: 'fruits-hub-ui.firebasestorage.app',
  );
}
